version: '2.2'
services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - KIBANA_PASSWORD=$KIBANA_PASSWORD
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m -Des.enforce.bootstrap.checks=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt"
      - "xpack.ssl.certificate=$CERTS_DIR/es01/es01.crt"
      - "xpack.ssl.key=$CERTS_DIR/es01/es01.key"
    volumes: ['esdata_01:/usr/share/elasticsearch/data', './certs:$CERTS_DIR']
    ports:
      - 192.168.99.100:9200:9200
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  kibana01:
    container_name: kibana01
    image: docker.elastic.co/kibana/kibana:6.2.2
    environment:
      - ELASTICSEARCH_URL=https://es01:9200
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$CERTS_DIR_K/ca/ca.crt
# Below option is not required.
#      - xpack.ssl.certificate_authorities=$CERTS_DIR_K/ca/ca.crt
    volumes: ['./certs:$CERTS_DIR_K']
# Host IP mapping is valid only for Docker Toolbox on Windows. Remove 192.168.99.100: from below port mapping if you are using docker for mac or docker for windows.
    ports:
      - 192.168.99.100:5601:5601

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2
    command: /usr/bin/true
    depends_on: {"es01": {"condition": "service_healthy"}}

  hippo01:
    container_name: hippo01
    image: cheddesi/onehippo-es-demo:latest
    #not required, cert is baked into the image itself.
    environment:
      - MYCA_CERT=$CERTS_DIR_K/ca/ca.crt
    depends_on:
      - es01
    volumes: ['./certs:$CERTS_DIR_K']
# Host IP mapping is valid only for Docker Toolbox on Windows. Remove 192.168.99.100: from below port mapping if you are using docker for mac or docker for windows.
    ports:
      - 192.168.99.100:8080:8080
volumes: {"esdata_01": {"driver": "local"}}
